---
- name: Exam1
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Content dest
      ansible.builtin.copy:
        content: exam1です
        dest: /home/ec2-user/ansible_on_vyos/ansible_practice/04-2_copy_file/copy_file_exam1.txt
        mode: "0644"

    - name: File delete
      ansible.builtin.file:
        path: /home/ec2-user/ansible_on_vyos/ansible_practice/04-2_copy_file/copy_file_exam1.txt
        state: absent
