---
- name: Exam3
  hosts: vyos01
  gather_facts: false

  tasks:
    - name: Get show commands
      vyos.vyos.vyos_command:
        commands:
          - show interfaces
          - show ip route
      register: vyos01_show_commands

    - name: Touch vyos01_show_ip_route.log 
      ansible.builtin.file:
        path: /home/ec2-user/ansible_on_vyos/ansible_practice/04-2_copy_file/vyos01_show_ip_route.log
        state: touch

    - name: Writing vyos01_show_ip_route.log
      ansible.builtin.copy:
        content: "{{ vyos01_show_commands.stdout[1] }}"
        dest: /home/ec2-user/ansible_on_vyos/ansible_practice/04-2_copy_file/vyos01_show_ip_route.log
