---
- name: Exam4
  hosts: all
  gather_facts: false

  tasks:
    - name: Make text file
      ansible.builtin.file:
        path: /tmp/test_exam4.txt
        state: touch
        mode: '0644'
      register: result
      when: inventory_hostname == 'host01'

    - name: Debug success msg
      ansible.builtin.debug:
        msg: "make success text!"
      when: inventory_hostname == 'host01' and result is succeeded
