---
- name: Sample_copy
  hosts: localhost
  gather_facts: false

  vars:
    sample_handson: テスト文です

  tasks:
    - name: Write text
      ansible.builtin.copy:
        content: "{{ sample_handson }}"
        dest: /home/ec2-user/ansible_on_vyos/ansible_practice/04-2_copy_file/handson.txt
        mode: "0644"
