---
- name: Sample_file
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Make directory
      ansible.builtin.file:
        path: /home/ec2-user/ansible_on_vyos/ansible_practice/04-2_copy_file/file_directory
        state: directory
        mode: "0644"
