---
- name: Sample2_set_fact
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Setting set_fact
      ansible.builtin.set_fact:
        test: "Hello Ansible!"

    - name: Setting set_fact debug
      ansible.builtin.debug:
        var: test
